#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

preset='default'
MAX_TOKENS=200
TIMEOUT=10

while getopts "p:l:t:" opt; do                                            
	case $opt in                                                            
		p)                                                                    
			preset=$OPTARG
			;;                                                                  
		l)                                                                    
			MAX_TOKENS=$OPTARG
			;;                                                                  
		t)                                                                    
			TIMEOUT=$OPTARG
			;;                                                                  

		\?)                                                                   
			echo "Invalid option: -$OPTARG" >&2                                 
			exit 1                                                              
			;;                                                                  
		:)                                                                    
			echo "Option -$OPTARG requires an argument." >&2                    
			exit 1                                                              
			;;                                                                  
	esac                                                                    
done


while true; do
	read -e -p " " content
	if [ "$content" == "exit" ]; then
		break
	fi
	if [ -v preset ]; then
		gpt_ping "$preset" "$content" -l $MAX_TOKENS -t $TIMEOUT | glow -s '/home/amda/.config/glow/gpt_style.json'
		unset preset
	else
		gpt_ping "$content" -m "$(cat $SCRIPT_DIR/log/discussion.txt)" -l $MAX_TOKENS -t $TIMEOUT | glow -s '/home/amda/.config/glow/gpt_style.json'
	fi
done
